apel/apel

- schemas/server.sql
Resolves #57.
- Change `INT` to `BIGINT` in the `ReplaceNormalisedSummary` procedure as the
portal was suffering from an integer overflow when loading the summaries
sent from the central APEL server.
> Change INT to BIGINT in a loading procedure

- bin/retrieve_dns.py
- conf/auth.cfg
- test/test_retrieve_dns.py
Resolves #60.
**Main changes:**
- Change `retrieve_dns` to keep the previous DN list if there isn't a valid
response from GOCDB. This is so that messages aren't rejected just
because there was a small period where GOCDB is unreachable.
- Add config option to alter the expiry time of the DN list when the above
situation occurs.
- Add lots of test cases for `retrieve_dns`. :triumph:
**Minor changes:**
- Change `retrieve_dns` to only print a debug message when it encounters a
comment line starting with "#" as there used to always be a few that
would generate warnings unnecessarily.
- Reorder `sys.exit` and `log.info` in `retrieve_dns` so that the logging call
is first otherwise it is never reached.
> Keep DNs if no valid response from GOCDB

- schemas/cloud.sql
Resolves #58.
- Add the columns Month and Year to the primary key for the CloudSummaries
table as these columns are part of the GROUP BY used to create the
summaries and so should be in the primary key, otherwise summaries will
overwrite each other.
> Add Month and Year to CloudSummaries primary key

- apel/parsers/sge.py
- test/test_sge.py
Replacement pull request for #36.
The GridEngine scheduler does not include any built-in solution to normalize the cputime/walltime numbers in a heterogeneous cluster. This change extends GridEngine's APEL parser to normalize these values according to the nodes' definition.
For each accounting record, cputime/walltime are computed based on the 'cputmult' and 'wallmult' (a la PBS) complex values set in the node's definition. If no multiplier is found, it defaults to 1.
> Add GridEngine multiplier capability to parser

- apel/db/loader/star_parser.py
Resolves #62.
Simple fix for missing logging. Follows same pattern as for the [car_parser](https://github.com/apel/apel/blob/dev/apel/db/loader/car_parser.py).
> Add logging to star_parser

- apel/db/records/record.py
- apel/parsers/lsf.py
- apel/parsers/sge.py
- bin/parser.py
- conf/parser.cfg
- test/test_parser.py
- test/test_record.py
- test/test_sge.py
Resolves #47.
- Add option to parser config that defines whether Grid Engine is using
millisecond timestamps as Univa Grid Engine is doing this from version
8.2.0. Will default to not converting the timestamp if the option is
absent.
- Add unit test for this new timestamp format and unit test for changes to `parser.py`.
- Move call to datetime function in `apel/db/records/record.py` to its own `try...except` block as it needs
different handling to the `int` call when raising a `ValueError`. In the former
case, it is likely to be a timestamp out of range (possibly caused by the
Grid Engine oddness) and having it masked by the error message of the `int` call was confusing.
- Make `test_record.py` directly runnable.
> Univa Grid Engine timestamp option

- apel/db/loader/loader.py
- test/test_loader.py
- test/test_retrieve_dns.py
Resolves #67.
- Added a bit more info to the log output when messages are saved or rejected so that the queue location is added to the log.
- Added the first unittests for `loader.py`.
- Also added a missing `os.remove` to a different test.
> Log entries for saved and rejected messages

- scripts/migrate_apel.py
- Change calculations for target month and year for setting the starting
point of the migration as the existing calculations didn't really work
over year boundaries.
> Fix to migrate_apel.py date calculation 

- conf/parser.cfg
Resolves #68.
- Change default for 'parallel' to true in parser config so that new
installations will default to parsing MPI data.
> Change default for 'parallel' to true

- bin/parser.py
Submitted in [this GGUS ticket](https://www.ggus.eu/index.php?mode=ticket_info&ticket_id=109162).
From commit message:
> It is much easier to skim over logs and search for some problems
> if you know that files are processed in some particular order.
> 
> Plain lexicographical sort is fine for all files that have YYYYMMDD
> as the non-constant part of the name: it coincides with sort by date
> that is the most natural thing.
> 
> Signed-off-by: AC
As I commented on the commit (see below), this is slower, but this step is only performed once per parser run and takes in the order of a couple of milliseconds, so I think this change is justified.
> Sort log files to be processed

- apel/parsers/htcondor.py
- bin/parser.py
- conf/parser.cfg
- scripts/htcondor_acc.sh
- test/test_htcondor_parser.py
Resolves #43.
Adds a basic HTCondor parser to APEL.
It's a meld of Pavel's and David's submissions, though the site-specific aspects of David's have been removed. Sites can customise the parser if they want to add in more specific functionality.
> HTCondor Parser

- test/test_loader.py
Change path to Queue class to explicitly go via its parent module as dirq version1.7 has removed the import of Queue in the `__init__.py`.
> Correct path to dirq Queue class

- apel/parsers/pbs.py
- test/test_pbs.py
Resolves #87.
- Add check for `wallduration` and `cput` being in seconds (though it just checks the latter) rather than
`hh:mm:ss` format as Torque 5.1.2 has changed to using the former. The parser then chooses what method to use to parse the duration fields meaning the change is backwards compatible.
- Add more test cases.
> Add support for Torque 5.1.2 time format

- apel/db/loader/aur_parser.py
- apel/db/loader/star_parser.py
- test/test_star_parser.py
Resolves #85.
- Change reference to CAR records to StAR records for exception message in
StAR record parser-loader.
- Change exception from plain `Exception` to `XMLParserException` for StAR and
AUR parser-loaders (to make sure it's consistent) as the plain `Exception` would not be caught by the
loader. CAR parser already uses the [right exception](https://github.com/apel/apel/blob/dev/apel/db/loader/car_parser.py#L48).
- Add corresponding unit test for StAR parser-loader.
> XML with no records crash fix

- apel.spec
- Add wilcard to end of `msg_status.py` when it is being packaged for the
server files so that newer versions of rpmbuild don't complain about
missing compiled Python files.
> Add missing files to package

- scripts/apel-client
Resolves #97.
Remove the file attribute arguments from the create directive in the logrotate script as there isn't necessarily an apel user on the system. Without the file attributes defined, the create directive defaults to using the same values as for the original log file.
See description for `create mode owner group` in the [logrotate man page](http://www.linuxcommand.org/man_pages/logrotate8.html).
> Remove args from create in logrotate script

- apel/parsers/pbs.py
- test/test_pbs.py
Resolves #100.
- The `exec_host` field in Torque >= 5.1.0 gives things like
`b391/0-1,5,11`,which is harder to parse, so for cores we can use the
`total_execution_slots` field instead for the number of cores.
- Add tests to cover this.
> Torque core count fix

- .travis.yml
- Remove Python 2.7 from allowed failures as we should now be building for
OSes that have it as default.
- Update Python 3.4 to 3.5 as we can just check the latest available (could check all versions of 3.x, but that's overkill for a version that doesn't work for us at the moment).
> Update Python versions in Travis file

- bin/summariser.py
Resolves #104.
- Disable duplicate sites check in summariser as it doesn't scale well and
it isn't that useful as it completely stops the summarising process if
it detects a site sending both job records and summaries.
This should perhaps be replaced with more useful checks later, but it's not worth the effort at the moment considering it has been disable on production machine for ages.
> Disable duplicate sites check in summariser

- bin/retrieve_dns.py
- test/test_retrieve_dns.py
- Adds method to retrieve the `next` link from fetched XML (or `None` if at last page or paging not in use)
- Adds test case for this method
- Moves `get_xml()` into a while loop, which ends when the `next` link is `None`
- Adds a mock `gocdb_url` for the `test_basics()` test case, as this now needs to be set, otherwise the while loop ends immediately, without fetching XML
- Passes Document Object Model (DOM) between methods to prevent parsing the same XML twice. 
- Renames `dns_from_xml` to `dns_from_dom` accordingly.
> Add support for GOCDB paging

- apel/parsers/pbs.py
- test/test_pbs.py
Reported on [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=125506).
Torque before version 5.0 used hh:mm:ss for `resources_used.walltime` and the later versions up to 5.1.2 use seconds. The field for `resources_used.cput` followed that change, but it seems that it didn't follow the latest change when 5.1.3 went back to hh:mm:ss for `walltime` so it produces logs with mixed time formats. This caused a problem as the software expects them to be of the same format.
This PR solves this by choosing separate time parsing functions for `walltime` and `cput` depending on their format. Tests updated alongside this.
> Another torque time change

- apel/db/backends/mysql.py
- apel/db/records/cloud_summary.py
- schemas/cloud.sql
- scripts/update_schema.sql
- test/test_cloud_summary.py
Resolves #103.
This PR updates the cloud accounting to include CPU count in the summaries that are sent to the portal. 
- The update schema (from adding support for schema v0.4) has been updated to include CPU count.
- I've even remembered to alter the number of arguments in the procedure call.
- Added it to `self._msg_fields` which is the key field for defining the unloaded messages.
> Cloud summary CPU count

- apel/common/datetime_utils.py
- apel/db/backends/mysql.py
- test/test_datetime_utils.py
Replace backslashes used for line continuation in Python code with implicit line continuation using parentheses as the former style is discouraged and is fragile.
There are places that use backslashes in shell code, but that's a separate issue.
> Replace backslashes with implicit line continuation

- apel.spec
Logrotate was in wrong section and lack of spacing was making the file hard to read.
> Tidy up SPEC file to make spacing more consistent

- .travis.yml
Change Travis file to test against latest nightly rather than a fixed Python 3 version so that it doesn't have to continually be manually changed.
At the moment this will be Python 3.7.0a0.
> Change Travis file to test against Python nightly

- .travis.yml
- requirements.txt
- Remove pip log before caching to avoid it affecting the cache.
- Add `--branch` argument to coverage run in preparation for coveralls
module reporting coverage to Coveralls.io.
- Add mock to requirements and add final newline.
> Travis tweaks

- apel/parsers/lsf.py
- test/test_lsf.py
Resolves #129.
- Remove LSF version restriction from LSF parser (where a TypeError would be raised if there was an unexpected version in the accounting log) as LSF has been well behaved over a number of major versions, it causes problems for users trying to upgrade to newer versions that haven't been tested, and we don't check versions in any other parser. This should remove the burden of updating the version mapping whenever a new LSF version is released.
- Remove unittest for invalid LSF version as version is no longer checked.
Site from GGUS ticket (see issue #129) has used this updated parser successfully.
> Remove LSF version restriction

- apel.spec
- Replace wildcard match with explicit excluding of `.pyc`/`.pyo` files
- The `.pyc`/`.pyo` files are auto-generated by `rpmbuild` so we can't stop them being generated and we cant just remove the wildcard because `rpmbuild` complains the `.pyc`/`.pyo` are present but not added to the RPM. So we need to explicitly exclude them from the RPM.
- 'exclude' is not the most documented spec file directive
> Prevent compiled python files from being installed by the RPM

- apel/db/backends/mysql.py
- schemas/cloud.sql
- test/test_mysql.py
This test, whilst passing and not adding to the code coverage, does reveal database warnings that become failures with stricter `sql_mode` settings, as referenced in #128.
This test will ensure the fix for #128 does not break the cloud loader, i.e by trying to pass a `NULL` benchmark to the database while `Benchmark` is a `NOT NULL` field), which is currently not caught by the unit tests.
Changes to `apel/db/backends/mysql.py`:
- will hopefully allow future equality testing of coud records pre and post database load in a similar fashion to job records by allowing `_get_records` to work for cloud records  
- it seems like `_get_records` only used in tests (i.e. `MYSQL_TABLES` is only mentioned in
`_get_records`/`get_records`, which are in turn only called in testing
> Add a test for loading cloud messages (from the APEL message format) to the database

- apel/db/loader/aur_parser.py
- apel/db/loader/xml_parser.py
- test/test_aur_parser.py
- test/test_car_parser.py
- test/test_xml_parser.py
- Main fix is to `xml_parser.py`. The `getTagByAttr` method in that should have been using the namespace it's given as an argument throughout (so that you can choose the namespace when you call it) but it was using `self.NAMESPACE` for one of the calls it makes and thus overriding your choice. This is the most significant change as it affects all the other XML parsers (StAR, CAR, AUR), but doesn't seem to have been a problem for the StAR parser as it uses a uniform namespace.
- Added a regression test for this.
- Tidied up the CAR parser.
- Fixed the AUR parser somewhat. It still doesn't work out normalised durations, but can now get Infrastructure, VOGroup, and VORole. (It's never really worked, to be fair! It's even disabled in `record_factory.py`.)
- Fixed the test for the AUR parser.
> Fixes to XML parsers

- apel/db/apeldb.py
- apel/parsers/__init__.py
- test/test_apeldb.py
- test/test_car_parser.py
- test/test_job_record.py
- test/test_logging.py
- test/test_lsf.py
- test/test_norm_sum_record.py
- test/test_parsers.py
- test/test_record_factory.py
- test/test_sge.py
- test/test_summary_record.py
This fixes a couple of very minor things that aren't even really bugs, and is mainly adding extra unittests to the ones that were straightforward to do. I'll just list the non-test changes here:
- Fix spacing and capitalisation of constructed queries in `apeldb` module to be more consistent and match standard SQL.
- Add `HTCondorParser` to `__init__` imports.
> Minor fixes and improved coverage

- apel/db/backends/mysql.py
- apel/db/records/storage.py
- apel/db/unloader.py
- conf/unloader.cfg
- schemas/storage.sql
- scripts/update-1.5.1-1.6.0.sql
- scripts/update-1.6.0-next.sql
- test/test_storage_record.py
- test/test_unloader.py
Resolves #108, resolves #109.
Changes in this PR:
- Add bits to unloader to enable unloading of StAR records in XML format.
- Add `VStarRecords` view.
- Extend the two update schemas to enable migration of old storage accounting databases.
The update schema changes were tested by creating a database for each version (1.5.1, 1.6.0, 1.6.1), running the relevant update script on them, then dumping the database and diffing the output (ignoring whitespace).
```
```
No significant differences between all three, though the two databases that had been updated had the additional default values in the `Roles` and `SubGroups` tables (as per the update schema) and so, interestingly, the table properties for them included `AUTO_INCREMENT=2` which sets the initial `AUTO_INCREMENT` value for the table …
> Storage fixes

- schemas/cloud.sql
- scripts/update-1.6.0-next.sql
For every field in the `GROUP BY` statement in the cloud summariser, it is possible two summaries could only differ by that field. If that field is not part of the primary key, one of those summaries would override the other.
This PR avoids this by adding all fields in the `GROUP BY` statement to the CloudSummaries table primary key.
It also provides an update script to upgrade existing installations.
> Add remaining fields that are in the cloud summariser 'GROUP BY' statement to the primary key

- apel/db/records/cloud.py
- apel/db/records/job.py
- apel/db/records/record.py
- test/test_cloud_record.py
- test/test_mysql.py
Resolves #128 
`Record._check_fields()` now checks fields listed in `self._float_fields` and `self._datetime_fields`  are the appropriate type, i.e. `float` or `datetime` in a similar fashion to how `self._int_fields` are currently handled. In the case of `self._float_fields` it will try and cast the input to a `float` if it is not already.
This results in properly typed fields or `None` to be passed to the database, rather than properly typed fields or the string `'None'`. 
This fixes the problem that MySQL 5.6.X has strict type checking and wont do the type casts that 5.1.X would.
The change to `apel/db/records/job.py` is due to the fact the `_check_factor` method is being passed `None` if ServiceLevel is missing (rather than the string `'None'`). The output of `_check_factor` is not …
> Add type checking to float and datetime fields of records

- apel/parsers/slurm.py
- test/test_slurm.py
As reported on [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=126954).
Not enough statuses are being accepted by the SLURM parser, so I've added all the ones that seem to indicate that the job has stopped and resources have been used.
Details on the statuses [here](https://slurm.schedmd.com/sacct.html). It's not the clear what some of them mean (mainly DEADLINE), but it should be a lot better than before.
Tested successfully by reporting user.
> Extra SLURM statuses

- README.md
- apel/parsers/lsf.py
- bin/parser.py
Remove references to specific LSF versions as that restriction has been
removed from the code a while ago (but the docs weren't updated).
> Remove references to specific LSF versions

- apel/db/records/cloud.py
- scripts/update-1.6.1-next_version.sql
- test/test_cloud_record.py
- test/test_mysql.py
The warnings are caused by CloudRecords with a NULL CpuCount forming CloudSummaries with a NULL CpuCount, which causes the warning because CpuCount is now part of the CloudSummaries primary key (following a bug fix in 1.6.1).
I have made a change to `cloud.py` to prevent new CloudRecords being loaded with a NULL CpuCount, opting for zero as the replacement, so CloudRecords without a CpuCount are as separate as possible from those that do.
I also added test cases to try and highlight what was changing and to show that everything still seems to work.
Tested by loading the below message repeatedly into a Cloud database (10.1.20-MariaDB) on a SL7 VM
```APEL-cloud-message: v0.4
BenchmarkType: HEPSPEC06
Status: completed
SiteName: Test Site
MachineName: Test Machine
ImageId: Test Image ID …
```
> Fix summariser time CpuCount warnings for cloud accounting

- apel/common/datetime_utils.py
- apel/parsers/slurm.py
- scripts/slurm_acc.sh
- test/test_slurm.py
Resolves #160.
This PR adds support for different time formats of CPU duration to be passed to the SLURM parser. This is to allow for the use of either `CPUTimeRAW` or `TotalCPU` from `sacct` which each have good and bad points depending on use case. I have decided not to enforce either format as the new field TotalCPU may not be so good for multicore jobs. **I've left it up to the user as to which they use.**
I've also added the different CPU time options to the `slurm_acc.sh` script, added unit tests, and tidied some whitespace.
> Add support for different CPU time fields for SLURM

- apel.spec
- scripts/apel-build-rpm
This PR has the following changes:
- Add comment in build script about using UMASK to allow the finished RPMs to be copied out by a non-root user. (e.g. on SCD Cloud VMs.)
- Capitalise VERSION in build script comment to match variable name.
- Replace repeated version numbers in SPEC file with equivalent tag so that we don't have to remember to update them regularly.
> Build tidy

- .travis.yml
- constraints.txt
- requirements-test.txt
- requirements.txt
As per apel/ssm#81.
- Move test requirements into separate requirements file to make it
clearer that they are only needed for running unit tests.
- Add constraints file called from the test requirements file to limit
one of coveralls' dependencies to an earlier version that works with
Python 2.6.
> Split test requirements out and add constraint

- setup.py
Resolves #165 
This prevents having to manually update the list of update scripts so long as the current naming convention continues.
I also took this opportunity to move the directory creation (`/var/log/apel` and `/var/run/apel`) into the `setup` call, rather than as hacky `if` statements.
> Use wildcard glob matching to ensure setup.py installs any update scripts under scripts, to match apel.spec 

- conf/unloader.cfg
specifically, clarify that `send_ur` is also used for storage accounting. As someone setting up a regional APEL server for storage accounting might not know that `send_ur` has to be true to unload storage records.
> Clarify what local_jobs and send_ur options do in unloader config

- bin/summariser.py
- conf/summariser.cfg
- constraints.txt
- test/test_summariser.py
Resolves #79 
Add a PID check to the summariser so that two summarisers of the same type can't be run at the same time. If the summariser finds it's Pidfile already exists, or it fails to create a new Pidfile, the summariser will now not run. At then end of the summariser run it tries to clean up the Pidfile and logs if the clean up fails.
Also adds a unit test of `bin/summariser.py` to test this new added functionality. This required a change to `bin/summariser.py` as `runprocess()` previously could not be run without running the python script.
> Add a PID check to the summariser and corresponding unit test 

- apel/parsers/htcondor.py
- test/test_htcondor_parser.py
The new, optional, cputmult factor will, if present in the accounting line, apply a
scaling factor to wall and cpu durations. If not present, the scaling factor defaults to 1.0, i.e. no
change. This will allow apelclient to be used in htcondorce deployments.
The unit test for htcondor.py has been expanded to include a run
with this feature. Existing sites who use (say) CREAM/HTCondor (who would not
include this new field) will be unaffected. The scheme described here:
https://twiki.cern.ch/twiki/bin/view/LCG/HTCondorAccounting
> New, optional, cputmult factor 

- CODEOWNERS
This file will mean that when a pull request is opened, everyone
in the code-reviewers team will be requested for review.
> Add basic CODEOWNERS file to simplify code reviews

- bin/client.py
- conf/client.cfg
Add manual_spec option to update the SpecLevels without any BDII. The code pulls out all config lines like these:
[spec_updater]
......
manual_spec0 = hepgrid6.ph.liv.ac.uk:9619/hepgrid6.ph.liv.ac.uk-condor,HEPSPEC,10.0
manual_spec1 = hepgrid24.ph.liv.ac.uk:9619/hepgrid6.ph.liv.ac.uk-condor,HEPSPEC,15.0
If lines are found, it checks that the site_name is configured, then verifies the data and uses db.update_spec to push them into the apel db SpecRecords table. This does all the work in one section of 30 lines of code. It changes no other parts of the system - all existing features are left exactly as they stand.
> Add manual_spec option to update the SpecLevels without any BDII.

- apel/db/records/cloud.py
Resolves #193 
As discussed in that issue, treat `Measurement{Time, Month, Year}` the same as `UpdateTime`, as they are all created in the database on load but we dont necessarily want them being unloaded.
> Add Measurement variables to cloud record ignored fields

- .travis.yml
- schemas/client.sql
- test/test_mysql.py
- Changes to Travis file bring our APEL CI into line with SSM (which was updated more recently).
- MySQL testing has been changed to use MariaDB defaults from 10.1.x as 10.2.x defaults don't work with the current schemas.
- Some fixes to the client schema required by non-ancient versions of MySQL (or just typos).
Lack of update script recorded in https://github.com/apel/apel/issues/243
> Travis, MySQL and testing fixes

- bin/summariser.py
Times how long the summariser takes to complete and outputs to the log when successful.
An example:
```
...
2021-01-25 16:17:38,692 - summariser - INFO - Summarising completed in: 0.014 seconds
2021-01-25 16:17:38,692 - summariser - INFO - ========================================
> Adds timer to summariser log

- requirements.txt
3.4.0 dropped support for Python 2
- https://github.com/python-ldap/python-ldap/releases/tag/python-ldap-3.4.0
> Cap python-ldap below 3.4.0

- apel.spec
Resolves #286 .
Decided to only add it to the RPM SPEC file as that's the package that is likely to be used on a Python 2 system, while the setup.py is likely to be used on a Python 3 system.
> Limit python-ldap version while we still need Py 2

- apel/ldap/query.py
- conf/client.cfg
- CERN BDII is being decommissioned so this changes it to the EGI one which is still available.
As requested by CERN ops.
> Update default hostname for BDII

- scripts/update-1.8.2-1.9.1.sql
Resolves #243 
Manually tested by comparing output of `SHOW CREATE TABLE` from an upgraded schema to the 1.9.1 schema.
> Add update schema

- test/test_mysql.py
- test/test_republish.py
This solves the MySQL-based tests from hanging in CI when using Python 3.
The basic issue was the connections not being closed.
> Fix mysql tests

- bin/parser.py
Minor change to @maxfischer2781 's commit, resolves #324  .  Adds a flag that checks if a file's been skipped, and sends a single non repeating message per scan_dir if this has occurred. 
Supersedes and closes #326.
> Verbosity fix

- test/test_hashing.py
I was doing some testing while building Apel and noticed this test just wasn't being called in the script, so this is a small little change to make it work.
> Fix to test function not being called on test script running.

- .github/workflows/build-pkgs.yml
Setting the version to just major.minor rather than major.minor.patch and letting the Action pull in the latest of the minor series should hopefully reduce the number of dependabot PRs a little while still giving us a good view on relevant changes.
Inspired by https://github.com/GOCDB/gocdb-failover-scripts/pull/30
And reminded by: https://github.com/apel/apel/pull/349
> Update and simplify upload-artifact action version

- .github/workflows/unit-test.yml
- .travis.yml
We have working Python 3 tests in GitHub Actions.
This will save on build credits, which we currently have to request from Travis.
> Remove redundant Python 3 test from Travis and add caching to GH Action

- apel/db/backends/mysql.py
- bin/summariser.py
- conf/summariser.cfg
To help with [this GUS ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=147103).
Resolves #217 by adding the option `enable_clean_up` to the `summariser.cfg` which, if `true` will trigger logic to delete stale cloud summaries reporting recent usage after the summariser has run. It also adds the option `newer_than` to allow a configurable definition of "recent", in terms of days.
**Manual testing**
with `enable_clean_up = true` and `newer_than = 2`
Lets say we have an old summary that is stale because we deleted the corresponding records as part of a retention policy.
```
MariaDB [217_test]> REPLACE INTO CloudSummaries (UpdateTime, SiteID, CloudComputeServiceID, Month, Year, GlobalUserNameID, VOID, VOGroupID, VORoleID, Status, CloudType, ImageId, CpuCount, BenchmarkType, …
```
> GT-149 Add support for deleting stale cloud summaries reporting recent usage.

- apel/ldap/query.py
Resolves: https://github.com/apel/apel/issues/375
Issue: Apel client fails with exception when tries to use startswith with string argument on items returned from LDAP, because they have different data type (array of bytes)
> [GT-450] Ldap returns byte and not string with python3

- apel/db/loader/loader.py
- test/test_loader.py
When user sends storage record starting with '<'. Previously it doesn't have the class type in `record_type`. Now it should say Storage if it is a storage record when it receives a file from receiver.
Resolves #238
> [#238] Add storage record type for logger

- bin/client.py
- bin/dbloader.py
- bin/dbunloader.py
- bin/parser.py
- bin/retrieve_dns.py
- bin/summariser.py
Optparse is deprecated - no longer developed. Mostly a like-for-like replacement, but we use vars on the argparse object to output the values in a similar way to optparse.
The old 'version' option on the constructor is unavailable, and so it has been replaced by adding an argument with the 'version' action.
Resolves #380 
Resolves GT-542
> Replace optparse with argparse

- apel/db/loader/record_factory.py
- apel/db/unloader.py
Resolves #393 
This PR;
- fixes the full header matching (on loading) to trim whitespace before matching to the list of headers, as trailing whitespace was throwing this off before leading to rejected messages.
- removes the space added by the unloader after header. Due to changes in the way the loader now works, this additional whitespace was causing messages to be rejected as the header wasn't being trimmed before matching. While the incoming header is now trimmed by the previous commit, the unloaded header shouldn't have a trailing space anyway.
> Fix trailing whitespace in header

- bin/summariser.py
Summariser sometimes complained about the temporary table already existing. This commit ensures the database connection is closed, avoiding hanging connections.
Resolves #392
> Close temporary table.

- apel/db/records/record.py
Asserts get skipped in compiled Python code, so shouldn't be relied on for normal checks within the code. Replace this with a check on the lengths and raise a ValueError if they don't match.
> Replace assert with proper check
