.travis.yml
requirements.txt

Travis has [added the ability to run builds on containerized infrastructure](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) (using Docker). This improves start up time and the speed of the builds.
These changes enable us to take advantage of this (plus some minor bits of reorganisation and commenting).
Docs for more info:
[Using container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/)
[Caching Dependencies and Directories](http://docs.travis-ci.com/user/caching/)

Containerize Travis

---

.travis.yml
test/test_mysql.py
test/test_schemas.py

This adds tests for the parts of the code that access MySQL (`test_mysql.py`) as well as checking the SQL syntax of the files in the `schemas` directory (`test_schemas.py`).

Add tests for MySQL parts and SQL syntax

---

apel/db/__init__.py
apel/db/backends/mysql.py
apel/db/records/cloud.py
apel/db/records/cloud_summary.py
schemas/cloud.sql
test/test_cloud_record.py
test/test_cloud_summary.py

This pull request just merges SP's cloud branch into an equivalent one in apel/apel.

Cloud v0.4 Integration

---

test/test_norm_sum_record.py

This adds a normalised summary record test based on the summary record test with a few minor tweaks so it's not very sophisticated, but at least it exercises some more of the code.

Adding normalised summary record test

---

setup.py

Resolves #86 
Adds a setup.py script to APEL, allows APEL packages to be installed on any OS that has Python installed

Add a setup script

---

CHANGELOG
apel.spec
apel/__init__.py
scripts/apel-build-rpm
scripts/update-1.6.0-1.6.1.sql

Do check this one for problems (spelling, version numbers, etc.) as it wouldn't have been reviewed in any other PR.

Release 1.6.1 to dev

---

.travis.yml
requirements-test.txt

- Small change as Codecov uses the same coverage tool as Coveralls.

Add Codecov coverage testing

---

conf/unloader.cfg

Add comment to withhold_dns unloader config option

---

apel/db/backends/mysql.py
apel/db/unloader.py
bin/dbunloader.py
conf/db.cfg
conf/unloader.cfg

Allow records per message to be configured in the DB unloader

---

README.md

Add logos and text for acknowledgements, using logos from the GOCDB repository.

Add EOSC-hub acknowledgement

---

apel/db/loader/loader.py
test/test_loader.py

loader.py adds type of record to logs, and update test_loader to confirm 
log call
Resolves #143

Log type of record being loaded

---

scripts/apel-build-rpm

Run rpmlint after building RPMs

---

apel.spec
bin/client.py

Resolves #230.
Depends on apel/ssm#149.

Refactoring SSM call to make client AMS compatible

---

.github/workflows/build-pkgs.yml

Remove trailing whitespace

---

README.md

Fix links to logos and badges

---

conf/loader.cfg

Delete accepted messages by default

---

.github/workflows/build-pkgs.yml
.github/workflows/codeql-analysis.yml
CHANGELOG
apel.spec
apel/__init__.py
apel/db/records/job.py
apel/ldap/query.py
conf/client.cfg
conf/loader.cfg
scripts/apel-build-rpm
scripts/update-1.8.2-1.9.1.sql
test/test_job_record.py

Release 1.9.2 to master

---

apel/db/backends/mysql.py
apel/db/loader/loader.py
apel/db/loader/record_factory.py
apel/db/records/record.py
bin/dbloader.py

A few Python 3 type fixes to support HEPscore changes

Update to use except..as from commas and fix print

---

.github/workflows/codeql-analysis.yml
.pre-commit-config.yaml

- Add a couple of extra tests.
- Update pygrep hook to latest.
- Add config for CI.

Update pre-commit config

---

bin/dbunloader.py
test/test_dbunloader.py

Another refactoring PR in aid of the HEPscore work.
- Python 3 compatability fixes.
- Tidy of imports.
- Factoring out setting the number of records per message.
- Unit test for new factored out function.

Dbunloader refactor

---

test/test_norm_sum_record.py

#335 needs to be merged first.

Fix indentation in norm sum test so all cases run

---

apel/db/loader/loader.py
apel/db/unloader.py
bin/parser.py
bin/retrieve_dns.py
bin/summariser.py
scripts/migrate_apel.py
test/test_aur_parser.py
test/test_blah.py
test/test_car_parser.py
test/test_hashing.py
test/test_htcondor_parser.py
test/test_logging.py
test/test_lsf.py
test/test_pbs.py
test/test_record_factory.py
test/test_slurm.py
test/test_star_parser.py

A variety of code quality improvements, including a minor bug in a unit test where `assertTrue` was being used instead of `assertEqual`.

Code quality

---

apel/common/hashing.py
bin/dbloader.py
bin/parser.py
constraints.txt
test/test_mysql.py

Mentions of using python versions before 2.7 have been updated to utilise features that are available in python 2.7+
Mentions of only python 2 have been ignored as 2.7 is included under it
Resolves #360

Updated pre python 2.7 code

---

.pre-commit-config.yaml

Resolves #330 
Plus updates a hook and adds a couple more checks.

Pre-commit update

---

apel/db/apeldb.py
apel/db/loader/star_parser.py
apel/db/records/job.py
apel/db/records/record.py
apel/ldap/query.py
apel/parsers/sge.py
test/test_car_parser.py

Resolves #356
Resolves GT-438
Made Max Fischer's suggested enhancements to apel

Integrate #354 suggestions

---

apel/db/records/job.py
apel/db/records/record.py
test/test_blah.py
test/test_parsing_utils.py

Resolves #374
In record.py added extra checks to prevent None type being used for fqan fields as Null should not be in the database for them
Added extra tests to ensure correct datatypes where used

Added extra checks for fqan fields

---

schemas/cloud.sql
scripts/update-x.x.x-x.x.x.sql

246 no cloudtype primary key

---

CHANGELOG
apel.spec
apel/__init__.py
scripts/apel-build-rpm
scripts/update-1.9.1-2.2.0.sql

Changes for release 2.2.0.
Resolves #258 (Included as the release branch makes the most sense for updating version numbers from the placeholders in the update schema).

Release 2.2.0 to dev
